### PR TITLE
Disable button "Copy To" in reply form

### LINKED ISSUE #903: wrong command: "copy to" saves a draft
When I write a message in a discussion, _copy to_ saves a draft instead of copying the message.
As I understand it, the copy function is not available yet, so the button should be greyed out and noninteractive? Instead it is producing the wrong command.

capture d ecran de 2018-05-03 15-06-04

### PR DESCRIPTION
**Pull request by MonsieurLanza**
Fixes #903

### CODE REVIEW

File: src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx [hunk 1]
```diff
@@ -174,7 +174,12 @@ class ReplyForm extends Component {
             >
               <Trans id="messages.compose.action.save">Save</Trans>
             </Button>
-            <Button className="m-reply__bottom-action" onClick={this.handleSave} icon="share-alt" responsive="icon-only">
+            <Button
+              className="m-reply__bottom-action"
+              icon="share-alt"
+              responsive="icon-only"
+              disabled
```
Comment (iamdey) [inline src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx]: I prefer commented instead of disabled.

Or notify "not yet implemented" is legit  too.

File: src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx [hunk 2]
```diff
@@ -174,7 +174,11 @@ class ReplyForm extends Component {
             >
               <Trans id="messages.compose.action.save">Save</Trans>
             </Button>
-            <Button className="m-reply__bottom-action" onClick={this.handleSave} icon="share-alt" responsive="icon-only">
+            // <Button
+            //   className="m-reply__bottom-action"
+            //   icon="share-alt"
+            //   responsive="icon-only"
+            // >
               <Trans id="messages.compose.action.copy">Copy to</Trans>
```
Comment (iamdey) [inline src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx]: these 2 lines should be commented too

Comment (iamdey) [reply src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx]: can you add a comment like `// XXX no api available yet` or so
